name: Lint and SonarQube

on:
  - push
  - pull_request

jobs:
  lint-and-sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install uv
          make install

      - name: Run linter
        run: |
          make lint

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
              -Dsonar.host.url=https://sonarcloud.io
              -Dsonar.projectKey=v1catalyst_my-the-project-83
              -Dsonar.organization=Vitali
              -Dsonar.sources=page_analyzer
              -Dsonar.exclusions=**/__pycache__/**,hexlet_code/**,templates/**